name: Check Broken Links

on:
  push:
    branches: [ main ] # Or your branch name
  # schedule:
  #   - cron: '0 0 * * 0'  # Uncomment for weekly checks

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruzickap/action-my-broken-link-checker@v2
        with:
          pages_path: './'  # Or the correct path to your files
          url: 'https://example.com'  # <--- Use a placeholder URL here
          cmd_params: '--skip-tls-verification --verbose --color=always'  # Corrected typo here
