name: Check Broken Links

on:
  push: # Or schedule: - cron: '0 0 * * 0' for weekly checks

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruzickap/action-my-broken-link-checker@v2
        with:
          pages_path: './'
          cmd_params: '--skip-tls-verification --verbose --color=always'
